### ISSUE TITLE
Fix some HTML

### ISSUE THREAD

**Issue by rafikiadmin** [savvy-coders/course-materials#13]
Page https://savvy-coders.gitbook.io/course-materials/wk2mod1
Has some text that is displaying as code.

**Comment by manavm1990** [comment]
Could you be more specific? Screenshot or an 'id' link?

**Comment by rafikiadmin** [comment]
Sorry. Here are the two spots. I am pretty sure you intended the second code box in each case to be normal text:
![image](https://user-images.githubusercontent.com/25962823/57982184-f3821f00-7a0f-11e9-8e25-358633b634de.png)
![image](https://user-images.githubusercontent.com/25962823/57982203-21fffa00-7a10-11e9-85a1-ceca66be01ea.png)

**Comment by manavm1990** [comment]
[Submitted](https://github.com/NAlexPear/savvy-course-materials/pull/15) Closing. Tx. 👍
