### ISSUE TITLE
Improve formatting of inline styles

### ISSUE THREAD

**Issue by ricealexander** [savvy-coders/course-materials#19]
**Wk1Mod2.md** and **Wk1Mod3.md** show examples using inline styles. I believe the inline-styles examples would be improved if there were spaces between CSS properties:

Instead of:
```html
<p style="font-size:300%;text-align:center;font-family:'Times New Roman';">This is by far the most important part of the page!</p>
```

It would be
```html
<p style="font-size:300%; text-align:center; font-family:'Times New Roman'">This is by far the most important part of the page!</p>
```

The spaces between give more focus to the individual key/value pairs.

**Comment by manavm1990** [comment]
Agreed.

**Comment by manavm1990** [comment]
Actually, with the additional points we are bringing topics and examples we are bringing in, it's not really feasible to spend much time at all on this 'inline styles' stuff.
In a future `commit`, it will be removed, FYI.

**Comment by manavm1990** [comment]
https://github.com/savvy-coders/course-materials/commit/8214b81eb8785580487769776759e7234c019565
